@Test public void testItWithExistClass() throws Exception {
assertThat(String.valueOf(result.getValue()),is("success"));
}