@Test(expected=RuntimeException.class) public void testCloseLastIteratorThrows() throws Exception {
}