@Test(expected=RuntimeException.class) public void testIteratorThrow() throws Exception {
}